<?php

namespace Tests;


/**
 *
 *
 * @author Marko Krüger <plant2code@marko-krueger.de>
 *
 */
class TestCase extends \PHPUnit\Framework\TestCase
{

    protected function setUp()
    : void
    {
        include_once(realpath(__DIR__ . '/../bootstrap.php'));

        parent::setUp(); // TODO: Change the autogenerated stub
    }
}