<?php
/*
 * Generated by PEG.js 0.10.x with phpegjs plugin
 *
 * http://pegjs.majda.cz/
 */

namespace Plant2Code\Parser\Diagram;

/* Useful functions: */

class Parser
{
    protected $classes;

    protected $relations;

    protected $input;

    public function __construct($input)
    {
        $this->input = $input;
    }

    public function parse()
    {
        $this->getClassStrings();
    }

    protected function getClassStrings()
    {
        $pattern = '~(?:abstract\s+)*class.*?{.*?\n}~s';
        $matches = [];
        preg_match_all($pattern, $this->input, $matches);

    }
}